- name: Block
  block:
    - name: INFO
      ansible.builtin.debug:
        msg: "Jailboxing {{ item.type }}/{{ item.name }}"

    - name: Jailbox container
      kubernetes.core.k8s_json_patch:
        api_key: "{{ ocp_token }}"
        host: "{{ ocp_url }}"
        validate_certs: false
        kind: "{{ item.type }}"
        namespace: "{{ item.namespace }}"
        name: "{{ item.name }}"
        patch:
          - op: add
            path: /spec/template/spec/runtimeClassName
            value: kata
  rescue:
    - name: Task failed
      ansible.builtin.debug:
        msg: "Jailobox failed for {{ item.name }}, going to the next pod"
