- name: INFO
  ansible.builtin.debug:
    msg: "Jailboxing {{ item.type }}/{{ item.name }}"

- name: Jailbox container
  kubernetes.core.k8s_json_patch:
    kind: "{{ item.type }}"
    namespace: "{{ item.namespace }}"
    name: "{{ item.name }}"
    patch:
      - op: add
        path: /spec/runtimeClassName
        value: kata
