apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 05-enable-criu
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            compression: ""
            source: data:,%5Bcrio.runtime%5D%0Aenable_criu_support%20%3D%20true%0A
          mode: 420
          overwrite: true
          path: /etc/crio/crio.conf.d/05-enable-criu