- name: Collect checkpoint data from running container
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Parse input params from EDA
      ansible.builtin.set_fact:
        __entity: "{{ alert
          | json_query('entity.*.{type: type, name: name, namespace: namespace}')
          | unique }}"
      when: run_local is not defined

    - name: Jailbox containers
      ansible.builtin.include_tasks: "tasks/jailbox_containers.yaml"
      with_items: "{{ __entity }}"
      when: do_jailbox is defined

    - name: JAILBOX Send notification message via Slack
      community.general.slack:
        token: "{{ slack_token }}"
        channel: "#levelup-eda-demo"
        msg: |-
          "🔴 🏴‍☠️ abnormal activity detected: 
            {{ __entity | to_nice_json(indent=2) }} 🏴‍☠️ 
          Entity has been jailboxed!"
